### ISSUE TITLE
Implement passThroughProps functionality for selective prop passing

### ISSUE THREAD

**Issue by rodleviton** [reactivepixels/recast#72]
## Feature Description

We need to implement a `passThroughProps` feature in Recast that allows specific variant and modifier props to be passed through to the base component. This feature will provide more control over which props are passed to the wrapped component and provide additional component level logic capabilities without the need to rewrap the component.

## Proposed Implementation

The `passThroughProps` option should be implemented as an array of strings in the `RecastConfig`:

```typescript
type RecastConfig<V, M> = {
  passThroughProps?: (keyof V | keyof M)[];
  // ... other config options
};
```

## Usage

The `passThroughProps` option should be used in the `recast` function as follows:

```typescript
const EnhancedComponent = recast(BaseComponent, styles, {
  passThroughProps: ["size", "color", "disabled"]
});
```

This configuration will allow the specified variant and modifier props ("size", "color", and "disabled" in this example) to be passed through to the base component.

## Required Functionality

1. When `passThroughProps` is specified, only the listed variant and modifier props should be passed through to the base component.
2. If a prop is listed in `passThroughProps` but not provided when the component is used, it should not be passed to the base component.
3. Props not specified in `passThroughProps` should not be passed through to the base component, even if they are provided when the component is used.
4. Base component props (those not related to variants or modifiers) should always be passed through, regardless of the `passThroughProps` configuration.

## Type Safety

Ensure that the `passThroughProps` array is type-checked to allow only valid variant and modifier prop names to be specified.

## Implementation Notes

- This feature should provide a way to selectively pass variant and modifier props to the base component.
- It should not affect how base component props are handled; these should always be passed through.
- The implementation does not need to distinguish between variant and modifier props in the `passThroughProps` array.

## Tasks

- [x] Update the `RecastConfig` type to include the `passThroughProps` option.
- [x] Modify the `recast` function to handle the `passThroughProps` configuration.
- [x] Implement the logic to filter props based on the `passThroughProps` array.
- [x] Add type checking to ensure only valid variant and modifier props can be specified in `passThroughProps`.
- [x] Write unit tests to verify the correct behavior of the `passThroughProps` feature.
- [ ] Update documentation to explain the usage and behavior of `passThroughProps`.

## Acceptance Criteria

- The `passThroughProps` option correctly filters which variant and modifier props are passed to the base component.
- Base component props are always passed through, regardless of `passThroughProps`.
- The feature is type-safe, allowing only valid prop names to be specified.
- Comprehensive unit tests cover all aspects of the `passThroughProps` functionality.
- Documentation clearly explains how to use and configure `passThroughProps`.

**Comment by rodleviton** [comment]
Closing as not planned. Recast is now archived and no longer maintained.

The problem this project set out to solve is well covered by [tailwind-variants](https://www.tailwind-variants.org/), [class-variance-authority](https://cva.style/) and [shadcn/ui](https://ui.shadcn.com/). Thanks for taking the time to file this.
